---

redis_version: 4.0.1
redis_mode: single
redis_disable_transparent_hugepage: true
redis_user: redis
redis_group: redis

#files
redis_install_path: "/opt/redis"  # redis source will be here
redis_conf_path: "/etc/redis"
redis_manager_template_path: instance-manager.sh.j2
redis_log_path: "/var/log/redis"

#service state
redis_service_state: started
redis_service_enabled: true
redis_install_new_version: false 

# configs
include_redis_default_conf: true

redis_save:
  - 900 1
  - 300 10
  - 60 10000

redis_confs:
  bind: "0.0.0.0"
  protected-mode: "no"
  port: "6379"
  pidfile: "/var/run/redis/redis.pid"
  loglevel: "notice"
  logfile: "{{ redis_log_path }}/redis.log"
  databases: "16"
  rdbcompression: "yes"
  rdbchecksum: "yes"
  supervised: "systemd"
  slave-serve-stale-data: "yes"
  slave-read-only: "yes"
  stop-writes-on-bgsave-error: "yes"
  appendonly: "yes"
  appendfilename: "appendonly-db.aof"
  dbfilename: "dump.rdb"
  daemonize: "no"
