---

- name: Nodejs Add Repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://deb.nodesource.com/node_8.x {{ ansible_lsb.codename }} main"
    - "deb-src http://deb.nodesource.com/node_8.x {{ ansible_lsb.codename }} main"

- name: Installing Nodejs
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - nodejs